@host=http://localhost:8080

##### Product API #####
GET {{host}}/v1/products HTTP/1.1

### 
GET {{host}}/v1/products?sort=price HTTP/1.1

### 
GET {{host}}/v1/products?sort=-price HTTP/1.1

###
GET {{host}}/v1/products?brandId=7 HTTP/1.1

### 
GET {{host}}/v1/products?brandId=11&pageNumber=2&pageSize=10 HTTP/1.1

###
GET {{host}}/v1/products/10 HTTP/1.1

###
GET {{host}}/v1/products/brands HTTP/1.1

##### Cart API #####
POST {{host}}/v1/carts HTTP/1.1
Content-Type: application/json

[
    {
        "productId": 2,
        "quantity": 1
    }
]